[package]
name = "rust-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
jsonrpsee = {version = "0.26.0", features = ["full"]}
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
tracing = "0.1.41"
tracing-subscriber = {version= "0.3.20", features=["env-filter"]}

